name: CI/CD Pipeline for main branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # === DETECT CHANGES ===
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      mjs-changed: ${{ steps.changes.outputs.mjs }}
      package-changed: ${{ steps.changes.outputs.package }}
      docs-changed: ${{ steps.changes.outputs.docs }}
      workflow-changed: ${{ steps.changes.outputs.workflow }}
      any-code-changed: ${{ steps.changes.outputs.code }}
      new-version: ${{ steps.changes.outputs.new-version }}
      version: ${{ steps.changes.outputs.version }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Detect changes and check version
      id: changes
      run: |
        # For PRs, compare against base branch; for pushes, compare with previous commit
        EVENT_NAME="${{ github.event_name }}"
        if [ "$EVENT_NAME" = "pull_request" ]; then
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          git fetch origin $BASE_SHA
          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA 2>/dev/null || echo "")
        else
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD 2>/dev/null || git ls-tree --name-only -r HEAD)
        fi
        
        echo "Changed files:"
        echo "$CHANGED_FILES"
        
        # Check for .mjs file changes
        if echo "$CHANGED_FILES" | grep -q '\.mjs$'; then
          echo "mjs=true" >> $GITHUB_OUTPUT
        else
          echo "mjs=false" >> $GITHUB_OUTPUT
        fi
        
        # Check for package.json changes
        if echo "$CHANGED_FILES" | grep -q '^package\.json$'; then
          echo "package=true" >> $GITHUB_OUTPUT
        else
          echo "package=false" >> $GITHUB_OUTPUT
        fi
        
        # Check for documentation changes
        if echo "$CHANGED_FILES" | grep -q '\.md$'; then
          echo "docs=true" >> $GITHUB_OUTPUT
        else
          echo "docs=false" >> $GITHUB_OUTPUT
        fi
        
        # Check for workflow changes
        if echo "$CHANGED_FILES" | grep -q '\.github/workflows/'; then
          echo "workflow=true" >> $GITHUB_OUTPUT
        else
          echo "workflow=false" >> $GITHUB_OUTPUT
        fi
        
        # Check for any code changes (.mjs, package.json, or workflows)
        if echo "$CHANGED_FILES" | grep -qE '\.(mjs|json|yml|yaml)$|\.github/workflows/'; then
          echo "code=true" >> $GITHUB_OUTPUT
        else
          echo "code=false" >> $GITHUB_OUTPUT
        fi
        
        # Check version status
        # Only check for new versions on main branch pushes
        if [ "${{ github.ref }}" != "refs/heads/main" ] || [ "${{ github.event_name }}" != "push" ]; then
          echo "Not a main branch push - skipping version check"
          echo "new-version=false" >> $GITHUB_OUTPUT
        else
          if [ ! -f "package.json" ]; then
            echo "new-version=false" >> $GITHUB_OUTPUT
            echo "No package.json found"
          else
            VERSION=$(node -p "require('./package.json').version")
            PACKAGE_NAME=$(node -p "require('./package.json').name")
            
            # Check if version is already published on NPM
            if npm view "$PACKAGE_NAME@$VERSION" version 2>/dev/null; then
              echo "Version $VERSION already published"
              echo "new-version=false" >> $GITHUB_OUTPUT
            else
              echo "New version $VERSION detected - will publish"
              echo "new-version=true" >> $GITHUB_OUTPUT
              echo "version=$VERSION" >> $GITHUB_OUTPUT
            fi
          fi
        fi
        
        # Debug output
        echo "============ Debug Output ============"
        echo "GitHub ref: ${{ github.ref }}"
        echo "Event name: ${{ github.event_name }}"
        echo "All outputs written to GITHUB_OUTPUT:"
        cat $GITHUB_OUTPUT || echo "Could not read GITHUB_OUTPUT"
        echo "======================================"

  # === COMPILATION & SYNTAX CHECKS ===
  test-compilation:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.any-code-changed == 'true' || needs.detect-changes.outputs.workflow-changed == 'true'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        
    - name: Test solve.mjs compilation
      run: |
        echo "Testing solve.mjs compilation..."
        timeout 30s node --check solve.mjs
        echo "✅ solve.mjs compiles successfully"
        
    - name: Test hive.mjs compilation
      run: |
        echo "Testing hive.mjs compilation..."
        timeout 30s node --check hive.mjs
        echo "✅ hive.mjs compiles successfully"
        
    - name: Check Node.js syntax for all .mjs files
      run: |
        echo "Checking syntax for all .mjs files..."
        for file in *.mjs; do
          if [ -f "$file" ]; then
            echo "Checking $file..."
            timeout 10s node --check "$file"
          fi
        done
        for file in tests/*.mjs; do
          if [ -f "$file" ]; then
            echo "Checking $file..."
            node --check "$file"
          fi
        done

  # === UNIT TESTS ===
  test-suites:
    runs-on: ubuntu-latest
    needs: [detect-changes, test-compilation]
    if: needs.detect-changes.outputs.any-code-changed == 'true' || needs.detect-changes.outputs.workflow-changed == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Run test suite for solve.mjs
      run: |
        echo "Running test suite for solve.mjs..."
        node tests/test-solve.mjs
    
    - name: Run test suite for hive.mjs
      run: |
        echo "Running test suite for hive.mjs..."
        node tests/test-hive.mjs
    
    - name: Run test suite for memory-check.mjs
      run: |
        echo "Running test suite for memory-check.mjs..."
        node tests/test-memory-check.mjs

    - name: Run feedback lines regression test (Issue #168)
      run: |
        echo "Running feedback lines regression test..."
        node tests/test-feedback-lines-simple.mjs

    - name: Run feedback lines integration test (Issue #168)
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_USER_TOKEN || secrets.GITHUB_TOKEN }}
        TEST_GITHUB_USERNAME: ${{ secrets.TEST_GITHUB_USERNAME }}
        TEST_GITHUB_USER_TOKEN: ${{ secrets.TEST_GITHUB_USER_TOKEN }}
      run: |
        echo "Running feedback lines integration test with real repository..."
        node tests/test-feedback-lines-integration.mjs

  # === EXECUTION TESTS ===
  test-execution:
    runs-on: ubuntu-latest
    needs: [detect-changes, test-compilation]
    if: needs.detect-changes.outputs.any-code-changed == 'true' || needs.detect-changes.outputs.workflow-changed == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Test solve.mjs execution
      run: |
        echo "Testing solve.mjs basic execution..."
        timeout 10s ./solve.mjs --help || echo "Help command completed"
        echo "✅ solve.mjs executes without critical errors"
        timeout 10s ./solve.mjs --version || true
    
    - name: Test hive.mjs execution
      run: |
        echo "Testing hive.mjs basic execution..."
        timeout 10s ./hive.mjs --help || echo "Help command completed"
        echo "✅ hive.mjs executes without critical errors"
        timeout 10s ./hive.mjs --version || true
    
    - name: Test memory-check.mjs execution
      run: |
        ./memory-check.mjs --help
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 --json

  # === MEMORY CHECKS - LINUX ===
  memory-check-linux:
    runs-on: ubuntu-latest
    needs: [detect-changes, test-compilation]
    if: needs.detect-changes.outputs.any-code-changed == 'true' || needs.detect-changes.outputs.workflow-changed == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: System info
      run: |
        echo "=== System Information ==="
        uname -a
        echo ""
        echo "=== Memory Information ==="
        free -h
        echo ""
        echo "=== Disk Information ==="
        df -h
        echo ""
        echo "=== CPU Information ==="
        lscpu | head -20
    
    - name: Run memory-check tests
      run: |
        chmod +x tests/test-memory-check.mjs
        node tests/test-memory-check.mjs
    
    - name: Test memory-check with various thresholds
      run: |
        echo "Testing with low thresholds (should pass)..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 --json
        
        echo ""
        echo "Testing verbose output..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100
        
        echo ""
        echo "Testing quiet mode..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 --quiet --json
    
    - name: Test memory-check failure conditions
      run: |
        echo "Testing with impossible memory requirement (should fail)..."
        if ./memory-check.mjs --min-memory 999999 --exit-on-failure --quiet --json; then
          echo "ERROR: Should have failed with impossible memory requirement"
          exit 1
        else
          echo "✅ Correctly failed with impossible memory requirement"
        fi
        
        echo ""
        echo "Testing with impossible disk requirement (should fail)..."
        if ./memory-check.mjs --min-disk-space 999999999 --exit-on-failure --quiet --json; then
          echo "ERROR: Should have failed with impossible disk requirement"
          exit 1
        else
          echo "✅ Correctly failed with impossible disk requirement"
        fi

  # === MEMORY CHECKS - MACOS ===
  memory-check-macos:
    runs-on: macos-latest
    needs: [detect-changes, test-compilation]
    if: needs.detect-changes.outputs.any-code-changed == 'true' || needs.detect-changes.outputs.workflow-changed == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: System info
      run: |
        echo "=== System Information ==="
        uname -a
        echo ""
        echo "=== Memory Information ==="
        vm_stat
        echo ""
        echo "=== Disk Information ==="
        df -h
        echo ""
        echo "=== Swap Information ==="
        sysctl vm.swapusage
        echo ""
        echo "=== CPU Information ==="
        sysctl -n machdep.cpu.brand_string
        sysctl hw.ncpu
    
    - name: Run memory-check tests
      run: |
        chmod +x tests/test-memory-check.mjs
        node tests/test-memory-check.mjs
    
    - name: Test memory-check with various thresholds
      run: |
        echo "Testing with low thresholds (should pass)..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 --json
        
        echo ""
        echo "Testing verbose output..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100
        
        echo ""
        echo "Testing quiet mode..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 --quiet --json
    
    - name: Test memory-check failure conditions
      run: |
        echo "Testing with impossible memory requirement (should fail)..."
        if ./memory-check.mjs --min-memory 999999 --exit-on-failure --quiet --json; then
          echo "ERROR: Should have failed with impossible memory requirement"
          exit 1
        else
          echo "✅ Correctly failed with impossible memory requirement"
        fi
        
        echo ""
        echo "Testing with impossible disk requirement (should fail)..."
        if ./memory-check.mjs --min-disk-space 999999999 --exit-on-failure --quiet --json; then
          echo "ERROR: Should have failed with impossible disk requirement"
          exit 1
        else
          echo "✅ Correctly failed with impossible disk requirement"
        fi
    
    - name: Test macOS-specific features
      run: |
        echo "Testing macOS swap detection..."
        output=$(./memory-check.mjs --min-memory 10 --quiet --json)
        if echo "$output" | grep -q '"swap"'; then
          echo "✅ Swap information detected in output"
        else
          echo "⚠️  Warning: Swap information not found in output"
        fi

  # === MEMORY CHECKS - WINDOWS ===
  # Temporarily disabled due to use-m bug on Windows: https://github.com/link-foundation/use-m/issues/45
  # The Windows support code is implemented but use-m fails to load on Windows
  memory-check-windows:
    runs-on: windows-latest
    needs: [detect-changes, test-compilation]
    # DISABLED: use-m doesn't work on Windows - see use-m-issues/issue-04-windows-fetch-undefined.mjs
    if: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: System info
      shell: cmd
      run: |
        echo === System Information ===
        systeminfo | findstr /C:"OS Name" /C:"OS Version" /C:"System Type"
        echo.
        echo === Memory Information ===
        REM wmic is deprecated in Windows Server 2025, use PowerShell instead
        powershell -Command "Get-CimInstance Win32_OperatingSystem | Select-Object TotalVisibleMemorySize, FreePhysicalMemory | Format-List"
        echo.
        echo === Disk Information ===
        powershell -Command "Get-CimInstance Win32_LogicalDisk | Select-Object Caption, Size, FreeSpace | Format-Table"
    
    - name: Test memory-check execution
      shell: bash
      run: |
        echo "Node version: $(node --version)"
        echo "Testing memory-check.mjs on Windows..."
        node ./memory-check.mjs --min-memory 10 --min-disk-space 100
        
        echo ""
        echo "Testing with JSON output..."
        node ./memory-check.mjs --min-memory 10 --min-disk-space 100 --json

  # === DOCUMENTATION VALIDATION ===
  validate-docs:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.docs-changed == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Validate documentation files
      run: |
        echo "Running documentation validation tests..."
        chmod +x tests/docs-validation.mjs
        node tests/docs-validation.mjs

  # === PUBLISH TO NPM ===
  publish:
    if: always()
    runs-on: ubuntu-latest
    needs: [detect-changes, test-compilation, test-suites, test-execution, memory-check-linux, memory-check-macos, validate-docs]
    permissions:
      contents: write  # Required for creating releases
      packages: write  # Required for publishing packages
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: 'https://registry.npmjs.org'
    
    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "${{ needs.detect-changes.outputs.new-version }}" != "true" ]; then
          echo "⊘ Publishing skipped (no new version detected)"
          echo "  new-version output: ${{ needs.detect-changes.outputs.new-version }}"
          exit 0
        fi
        
        echo "✓ New version detected, proceeding with publish"
        
        # Make scripts executable
        chmod +x hive.mjs
        chmod +x solve.mjs
        
        # Publish to NPM
        npm publish --access public
        
        # Create GitHub Release
        VERSION=${{ needs.detect-changes.outputs.version }}
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        gh release create "v${VERSION}" \
          --title "${VERSION}" \
          --notes "https://www.npmjs.com/package/${PACKAGE_NAME}/v/${VERSION}"