name: Memory Check Cross-Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run once a day at midnight UTC to ensure it stays working
    - cron: '0 0 * * *'

jobs:
  memory-check-linux:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: System info
      run: |
        echo "=== System Information ==="
        uname -a
        echo ""
        echo "=== Memory Information ==="
        free -h
        echo ""
        echo "=== Disk Information ==="
        df -h
        echo ""
        echo "=== CPU Information ==="
        lscpu | head -20
    
    - name: Run memory-check tests
      run: |
        chmod +x tests/test-memory-check.mjs
        node tests/test-memory-check.mjs
    
    - name: Test memory-check with various thresholds
      run: |
        echo "Testing with low thresholds (should pass)..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 --json
        
        echo ""
        echo "Testing verbose output..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100
        
        echo ""
        echo "Testing quiet mode..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 --quiet --json
    
    - name: Test memory-check failure conditions
      run: |
        echo "Testing with impossible memory requirement (should fail)..."
        if ./memory-check.mjs --min-memory 999999 --quiet --json; then
          echo "ERROR: Should have failed with impossible memory requirement"
          exit 1
        else
          echo "✅ Correctly failed with impossible memory requirement"
        fi
        
        echo ""
        echo "Testing with impossible disk requirement (should fail)..."
        if ./memory-check.mjs --min-disk-space 999999999 --quiet --json; then
          echo "ERROR: Should have failed with impossible disk requirement"
          exit 1
        else
          echo "✅ Correctly failed with impossible disk requirement"
        fi

  memory-check-macos:
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: System info
      run: |
        echo "=== System Information ==="
        uname -a
        echo ""
        echo "=== Memory Information ==="
        vm_stat
        echo ""
        echo "=== Disk Information ==="
        df -h
        echo ""
        echo "=== Swap Information ==="
        sysctl vm.swapusage
        echo ""
        echo "=== CPU Information ==="
        sysctl -n machdep.cpu.brand_string
        sysctl hw.ncpu
    
    - name: Run memory-check tests
      run: |
        chmod +x tests/test-memory-check.mjs
        node tests/test-memory-check.mjs
    
    - name: Test memory-check with various thresholds
      run: |
        echo "Testing with low thresholds (should pass)..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 --json
        
        echo ""
        echo "Testing verbose output..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100
        
        echo ""
        echo "Testing quiet mode..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 --quiet --json
    
    - name: Test memory-check failure conditions
      run: |
        echo "Testing with impossible memory requirement (should fail)..."
        if ./memory-check.mjs --min-memory 999999 --quiet --json; then
          echo "ERROR: Should have failed with impossible memory requirement"
          exit 1
        else
          echo "✅ Correctly failed with impossible memory requirement"
        fi
        
        echo ""
        echo "Testing with impossible disk requirement (should fail)..."
        if ./memory-check.mjs --min-disk-space 999999999 --quiet --json; then
          echo "ERROR: Should have failed with impossible disk requirement"
          exit 1
        else
          echo "✅ Correctly failed with impossible disk requirement"
        fi
    
    - name: Test macOS-specific features
      run: |
        echo "Testing macOS swap detection..."
        output=$(./memory-check.mjs --min-memory 10 --quiet --json)
        if echo "$output" | grep -q '"swap"'; then
          echo "✅ Swap information detected in output"
        else
          echo "⚠️  Warning: Swap information not found in output"
        fi

  memory-check-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: System info
      shell: cmd
      run: |
        echo === System Information ===
        systeminfo | findstr /C:"OS Name" /C:"OS Version" /C:"System Type"
        echo.
        echo === Memory Information ===
        wmic OS get TotalVisibleMemorySize,FreePhysicalMemory
        echo.
        echo === Disk Information ===
        wmic logicaldisk get size,freespace,caption
    
    - name: Test memory-check execution
      shell: bash
      run: |
        # Basic test on Windows - may have limited functionality
        echo "Testing basic execution on Windows..."
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 || true
        
        echo ""
        echo "Note: Full functionality may be limited on Windows"