name: Publish to NPM and GitHub Releases

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases
      packages: write  # Required for publishing packages
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Get package version
      id: package
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
    - name: Check if version is published
      id: version_check
      run: |
        VERSION=$(node -p "require('./package.json').version")
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        if npm view "$PACKAGE_NAME@$VERSION" version 2>/dev/null; then
          echo "already_published=true" >> $GITHUB_OUTPUT
        else
          echo "already_published=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Make scripts executable
      if: steps.version_check.outputs.already_published == 'false'
      run: |
        chmod +x hive.mjs
        chmod +x solve.mjs
        
    - name: Publish to NPM
      if: steps.version_check.outputs.already_published == 'false'
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release
      if: steps.version_check.outputs.already_published == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${{ steps.package.outputs.version }}
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        gh release create "v${VERSION}" \
          --title "${VERSION}" \
          --notes "https://www.npmjs.com/package/${PACKAGE_NAME}/v/${VERSION}"