name: Test Compilation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-compilation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Test solve.mjs compilation
      run: |
        echo "Testing solve.mjs compilation..."
        timeout 30s node --check solve.mjs
        echo "✅ solve.mjs compiles successfully"
        
    - name: Test hive.mjs compilation
      run: |
        echo "Testing hive.mjs compilation..."
        timeout 30s node --check hive.mjs
        echo "✅ hive.mjs compiles successfully"
        
    - name: Test solve.mjs execution (basic check)
      run: |
        echo "Testing solve.mjs basic execution..."
        timeout 10s node solve.mjs --help || echo "Help command completed"
        echo "✅ solve.mjs executes without critical errors"
        
    - name: Test hive.mjs execution (basic check)
      run: |
        echo "Testing hive.mjs basic execution..."
        timeout 10s node hive.mjs --help || echo "Help command completed"
        echo "✅ hive.mjs executes without critical errors"