name: Comprehensive Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-compilation:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Test solve.mjs compilation
      run: |
        echo "Testing solve.mjs compilation..."
        timeout 30s node --check solve.mjs
        echo "✅ solve.mjs compiles successfully"
        
    - name: Test hive.mjs compilation
      run: |
        echo "Testing hive.mjs compilation..."
        timeout 30s node --check hive.mjs
        echo "✅ hive.mjs compiles successfully"
        
    - name: Check Node.js syntax for all .mjs files
      run: |
        echo "Checking syntax for all .mjs files..."
        for file in *.mjs; do
          if [ -f "$file" ]; then
            echo "Checking $file..."
            timeout 10s node --check "$file"
          fi
        done
        for file in tests/*.mjs; do
          if [ -f "$file" ]; then
            echo "Checking $file..."
            node --check "$file"
          fi
        done
    
    - name: Run solve.mjs tests
      run: |
        chmod +x tests/test-solve.mjs
        node tests/test-solve.mjs
    
    - name: Run hive.mjs tests
      run: |
        chmod +x tests/test-hive.mjs
        node tests/test-hive.mjs
    
    - name: Test lib.mjs imports
      run: |
        node -e "import('./lib.mjs').then(() => console.log('✅ lib.mjs imports successfully'))"
    
    - name: Test github.lib.mjs imports
      run: |
        node -e "import('./github.lib.mjs').then(() => console.log('✅ github.lib.mjs imports successfully'))"
    
    - name: Test claude.lib.mjs imports
      run: |
        node -e "import('./claude.lib.mjs').then(() => console.log('✅ claude.lib.mjs imports successfully'))"
    
    - name: Test memory-check.mjs imports
      run: |
        node -e "import('./memory-check.mjs').then(() => console.log('✅ memory-check.mjs imports successfully'))"

  test-execution:
    runs-on: ubuntu-latest
    needs: test-compilation
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Test solve.mjs execution (basic check)
      run: |
        echo "Testing solve.mjs basic execution..."
        timeout 10s ./solve.mjs --help || echo "Help command completed"
        echo "✅ solve.mjs executes without critical errors"
    
    - name: Test solve.mjs --version
      run: |
        timeout 10s ./solve.mjs --version || true
    
    - name: Test hive.mjs execution (basic check)
      run: |
        echo "Testing hive.mjs basic execution..."
        timeout 10s ./hive.mjs --help || echo "Help command completed"
        echo "✅ hive.mjs executes without critical errors"
    
    - name: Test hive.mjs --version
      run: |
        timeout 10s ./hive.mjs --version || true
    
    - name: Test memory-check.mjs --help
      run: |
        ./memory-check.mjs --help
    
    - name: Test memory-check.mjs basic execution
      run: |
        ./memory-check.mjs --min-memory 10 --min-disk-space 100 --json

  test-suites:
    runs-on: ubuntu-latest
    needs: test-compilation
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Run test suite for solve.mjs
      run: |
        echo "Running test suite for solve.mjs..."
        node tests/test-solve.mjs
    
    - name: Run test suite for hive.mjs
      run: |
        echo "Running test suite for hive.mjs..."
        node tests/test-hive.mjs
    
    - name: Run test suite for memory-check.mjs
      run: |
        echo "Running test suite for memory-check.mjs..."
        node tests/test-memory-check.mjs